### PR TITLE
Ruff implementation

### LINKED ISSUE #65: Ruff implementation
## Description

The project has a poor CI (Continuous Integration) at the time, and this issue is dedicated for adding a simple CI for linting the project and formatting with [Ruff](https://docs.astral.sh/ruff/). This tool is a new absurdly fast all-in-one tool for linting and formatting, which means we don't need to set up other tools (e.g., isort, black, flake8, etc.)

### PR DESCRIPTION
**Pull request by zenthm**
## Description

This PR implements Ruff for linting and possibly formatting the project.

> *An extremely fast Python linter and code formatter, written in Rust*

### Changes:

- **Development `lint` dependencies**: Which includes Ruff (will only be installed for developers).
- **Ruff configuration**: This configures Ruff to select *all* rule, but ignore some rules and the `tests` directory.
- **PDM lint script**: A new script `lint`, has been added and can be run via `pdm run lint` (only available for developers).
- **GitHub lint workflow**: A new workflow for linting the project via CI with Ruff.
- **PDM lock file update**: Since there's a new development `lint` dependencies which includes Ruff.
- **Removal of `ci_check` workflow**: The new lint workflow replaces the `ci_check` workflow.

### Notes:

I did *not* formatted the project, but configured Ruff and replaced the `ci_check` workflow with a new lint workflow. Also, I didn't add a PDM script for formatting the project, you can format it by `ruff check (--fix) (--unsafe-fixes)`. There's hundreds of linting problems in the codebase like missing annotations which can't be fixed by Ruff and have to be done manually. These changes resolves #65.

### CODE REVIEW

**Comment by zenthm** [comment]
Uhm, I made `dev` as the base branch for merging. Switch it to `main` if you want.

**Comment by zenthm** [comment]
This seems to have conflict with the last changes in the `dev` branch.

**Comment by zenthm** [comment]
One more thing:

> The Ruff formatter is designed to be a drop-in replacement for Black. Specifically, the formatter is intended to emit near-identical output when run over Black-formatted code.

**Comment by dimkauzh** [comment]
I'm closing this pull request as it is now manually commited.

**Pull request closed without merging**
